#!/bin/bash

utility_container=`lxc-ls | grep utility`

echo "============================================================="
echo "openrc"
echo "============================================================="
set -x
lxc-attach -n $utility_container cat /root/openrc | tee ~/.ostrich/openrc
set +x

. ~/.ostrich/openrc
echo "============================================================="
echo "curl OS_AUTH_URL"
echo "============================================================="
set -x
curl $OS_AUTH_URL
set +x
echo
echo

echo "============================================================="
echo "catalog list"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd openstack catalog list
set +x
echo

echo "============================================================="
echo "endpoint list"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd openstack endpoint list
set +x
echo

echo "============================================================="
echo "server list"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd openstack server list
set +x
echo

echo "============================================================="
echo "image list"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd openstack image list
set +x
echo

echo "============================================================="
echo "baremetal node list"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd openstack baremetal list
set +x
echo
