#!/bin/bash -e

# $1: OSA branch (stable/mitaka, etc)

echo "============================================================="
echo "baremetal node list"
echo "============================================================="
set -x

if [ "$1" != "stable/mitaka" ]
then
  SSLOPTS="--insecure"
  CMD="node list"
else
  SSLOPTS=""
  CMD="list"
fi

timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack $SSLOPTS baremetal $CMD
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "EOF"
echo "============================================================="
