#!/bin/bash -e

utility_container=`lxc-ls | grep utility`

echo "============================================================="
echo "openrc"
echo "============================================================="
set -x
lxc-attach -n $utility_container cat /root/openrc | tee ~/.ostrich/openrc
cp -Rp /etc/openstack_deploy ~/.ostrich/
chmod -R ugo+r ~/.ostrich
set +x

. ~/.ostrich/openrc
echo "============================================================="
echo "curl OS_AUTH_URL"
echo "============================================================="
set -x
/opt/openstack-ansible/scripts/os-cmd curl -m 10 $OS_AUTH_URL
set +x
echo
echo

echo "============================================================="
echo "catalog list"
echo "============================================================="
set -x
timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack catalog list
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "endpoint list"
echo "============================================================="
set -x
timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack endpoint list
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "server list"
echo "============================================================="
set -x
timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack server list
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "image list"
echo "============================================================="
set -x
timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack image list
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "baremetal node list"
echo "============================================================="
set -x
timeout 30 /opt/openstack-ansible/scripts/os-cmd openstack baremetal list
echo "Exit code: $?"
set +x
echo

echo "============================================================="
echo "EOF"
echo "============================================================="
