#!/bin/bash -x

# $1: netblock (e.g. 192.168.51.0/24)
# $2: gateway (e.g. 192.168.51.1)
# $3: allocation range start
# $4: allocation range end


NET_ID=$(/opt/openstack-ansible/scripts/os-cmd neutron net-create --shared --provider:network_type flat --provider:physical_network ironic ironic_net | awk '/ id/ {print $4}')
SUBNET_ID=$(/opt/openstack-ansible/scripts/os-cmd neutron subnet-create $NET_ID $1 --name ironic_subnet --ip-version=4 \
--gateway=$2 --allocation-pool start=$3,end=$4 --enable-dhcp | awk '/ id/ {print $4}')

echo "Created network $NET_ID, subnet $SUBNET_ID"
